# Generated by Django 4.2.1 on 2024-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0003_userprofile_sync_token_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='html_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
