# Generated by Django 4.2.1 on 2024-10-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0004_alter_event_html_link_alter_event_organizer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='sync_token',
            new_name='google_sync_token',
        ),
        migrations.AddField(
            model_name='event',
            name='include_in_next_daily_story',
            field=models.BooleanField(default=False),
        ),
    ]
