# Generated by Django 4.2.1 on 2024-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calenders', '0005_rename_sync_token_userprofile_google_sync_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='include_in_next_daily_story',
            new_name='in_time_window',
        ),
        migrations.AddField(
            model_name='event',
            name='wanted_by_the_user',
            field=models.BooleanField(default=True),
        ),
    ]
